apiVersion: apps/v1
kind: Deployment
metadata:
  name: degraded-app
spec:
  selector:
    matchLabels:
      app: degraded-app
  template:
    metadata:
      labels:
        app: degraded-app
    spec:
      initContainers:
      - name: init
        image: ubuntu
        command: ['bash', '-c', 'exit 1;']
      containers:
      - image: ubuntu
        command: ['bash', '-c', 'exit 1;']
        imagePullPolicy: IfNotPresent
        name: ubuntu
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
      restartPolicy: Always

