apiVersion: apps/v1
kind: Pod
metadata:
  name: degraded-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: degraded-app
  template:
    metadata:
      labels:
        app: degraded-app
    spec:
      containers:
      - name: degraded-app
        image: ubuntu
        command: ["/bin/sh", "-c", "exit 1"]
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
        restartPolicy: Never

