# BEGIN: 5f3c8d2f7d8d
apiVersion: apps/v1
kind: Deployment
metadata:
  name: progressing-app
spec:
  selector:
    matchLabels:
      app: progressing-app
  template:
    metadata:
      labels:
        app: progressing-app
    spec:
      initContainers:
      - name: wait-for-indefinitely
        image: ubuntu
        command: ['bash', '-c', 'exit 1;']
      containers:
      - image: ubuntu
        command: ['bash', '-c', 'while true; do sleep 30; done;']
        imagePullPolicy: IfNotPresent
        name: ubuntu
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
            #restartPolicy: Always
# END: 5f3c8d2f7d8d

